---
name: Publish Beta
on:
  push:
    branches:
      includes:
        - "*"
      exclude:
        - main
permissions: write-all
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup npm
        run: >
          npm set @cyber_leo:registry=https://registry.npmjs.org

          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}"
      - name: Version and publish beta
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@cybergenios.com.br"
          yarn
          npx lerna run tsc
          lerna publish --canary --preid dev -y
