name: Publish

on:
  push:
    branch:
      - qa

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: smartlyio/lerna-publish-action@v2
      with:
        bump: major
        registry: "https://npm.pkg.github.com/leonunes-cyber"
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        AUTH_TOKEN_STRING: ${{ format('//npm.pkg.github.com/:_authToken={0}', secrets.GIT_TOKEN) }}
        GIT_DEPLOY_KEY: ${{ secrets.GIT_TOKEN }}