name: Publish

on:
  push:
    branch:
      - qa

jobs:
  publish:
    runs-on: ubuntu-latest
 
  
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: "test" # Interesting step
      run: ls

    - name: "Version and publish" # Interesting step
      env:
        GH_TOKEN: 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
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@cybergenios.com.br"
        npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes && npx lerna publish from-git --yes
