name: Publish

on:
  push:
    branch:
      - qa

jobs:
  publish:
    runs-on: ubuntu-latest
 
  
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        yarn install
    - uses: smartlyio/lerna-publish-action@v2
      with:
        bump: major
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}